version: '3'

services:
  blockchain:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${CONTAINER_NAME}

    ports:
      - "${SSH_PORT}:22"
    volumes:
      - ${PROJECT_PATH}:/app/
    env_file:
      - .env
